<?php
/**
 * GetPromoDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;

use \ArrayAccess;
use \YandexMarketApi\ObjectSerializer;

/**
 * GetPromoDTO Class Doc Comment
 *
 * @category Class
 * @description Информация об акции.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetPromoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetPromoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'period' => '\YandexMarketApi\Model\PromoPeriodDTO',
        'participating' => 'bool',
        'assortment_info' => '\YandexMarketApi\Model\GetPromoAssortmentInfoDTO',
        'mechanics_info' => '\YandexMarketApi\Model\GetPromoMechanicsInfoDTO',
        'bestseller_info' => '\YandexMarketApi\Model\GetPromoBestsellerInfoDTO',
        'channels' => '\YandexMarketApi\Model\ChannelType[]',
        'constraints' => '\YandexMarketApi\Model\GetPromoConstraintsDTO'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'period' => null,
        'participating' => null,
        'assortment_info' => null,
        'mechanics_info' => null,
        'bestseller_info' => null,
        'channels' => null,
        'constraints' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'name' => false,
		'period' => false,
		'participating' => false,
		'assortment_info' => false,
		'mechanics_info' => false,
		'bestseller_info' => false,
		'channels' => true,
		'constraints' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'period' => 'period',
        'participating' => 'participating',
        'assortment_info' => 'assortmentInfo',
        'mechanics_info' => 'mechanicsInfo',
        'bestseller_info' => 'bestsellerInfo',
        'channels' => 'channels',
        'constraints' => 'constraints'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'period' => 'setPeriod',
        'participating' => 'setParticipating',
        'assortment_info' => 'setAssortmentInfo',
        'mechanics_info' => 'setMechanicsInfo',
        'bestseller_info' => 'setBestsellerInfo',
        'channels' => 'setChannels',
        'constraints' => 'setConstraints'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'period' => 'getPeriod',
        'participating' => 'getParticipating',
        'assortment_info' => 'getAssortmentInfo',
        'mechanics_info' => 'getMechanicsInfo',
        'bestseller_info' => 'getBestsellerInfo',
        'channels' => 'getChannels',
        'constraints' => 'getConstraints'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('period', $data ?? [], null);
        $this->setIfExists('participating', $data ?? [], null);
        $this->setIfExists('assortment_info', $data ?? [], null);
        $this->setIfExists('mechanics_info', $data ?? [], null);
        $this->setIfExists('bestseller_info', $data ?? [], null);
        $this->setIfExists('channels', $data ?? [], null);
        $this->setIfExists('constraints', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['period'] === null) {
            $invalidProperties[] = "'period' can't be null";
        }
        if ($this->container['participating'] === null) {
            $invalidProperties[] = "'participating' can't be null";
        }
        if ($this->container['assortment_info'] === null) {
            $invalidProperties[] = "'assortment_info' can't be null";
        }
        if ($this->container['mechanics_info'] === null) {
            $invalidProperties[] = "'mechanics_info' can't be null";
        }
        if ($this->container['bestseller_info'] === null) {
            $invalidProperties[] = "'bestseller_info' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Идентификатор акции.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Название акции.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets period
     *
     * @return \YandexMarketApi\Model\PromoPeriodDTO
     */
    public function getPeriod()
    {
        return $this->container['period'];
    }

    /**
     * Sets period
     *
     * @param \YandexMarketApi\Model\PromoPeriodDTO $period period
     *
     * @return self
     */
    public function setPeriod($period)
    {
        if (is_null($period)) {
            throw new \InvalidArgumentException('non-nullable period cannot be null');
        }
        $this->container['period'] = $period;

        return $this;
    }

    /**
     * Gets participating
     *
     * @return bool
     */
    public function getParticipating()
    {
        return $this->container['participating'];
    }

    /**
     * Sets participating
     *
     * @param bool $participating Участвует или участвовал ли продавец в этой акции.  Для текущих и будущих акций возвращается со значением `true`, если в акции есть товары, которые были добавлены вручную. Если товары не участвуют в акции или добавлены в нее автоматически, параметр возвращается со значением `false`.  Для прошедших акций всегда возвращается со значением `true`.  Об автоматическом и ручном добавлении товаров в акцию читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/marketing/promos/market/index).
     *
     * @return self
     */
    public function setParticipating($participating)
    {
        if (is_null($participating)) {
            throw new \InvalidArgumentException('non-nullable participating cannot be null');
        }
        $this->container['participating'] = $participating;

        return $this;
    }

    /**
     * Gets assortment_info
     *
     * @return \YandexMarketApi\Model\GetPromoAssortmentInfoDTO
     */
    public function getAssortmentInfo()
    {
        return $this->container['assortment_info'];
    }

    /**
     * Sets assortment_info
     *
     * @param \YandexMarketApi\Model\GetPromoAssortmentInfoDTO $assortment_info assortment_info
     *
     * @return self
     */
    public function setAssortmentInfo($assortment_info)
    {
        if (is_null($assortment_info)) {
            throw new \InvalidArgumentException('non-nullable assortment_info cannot be null');
        }
        $this->container['assortment_info'] = $assortment_info;

        return $this;
    }

    /**
     * Gets mechanics_info
     *
     * @return \YandexMarketApi\Model\GetPromoMechanicsInfoDTO
     */
    public function getMechanicsInfo()
    {
        return $this->container['mechanics_info'];
    }

    /**
     * Sets mechanics_info
     *
     * @param \YandexMarketApi\Model\GetPromoMechanicsInfoDTO $mechanics_info mechanics_info
     *
     * @return self
     */
    public function setMechanicsInfo($mechanics_info)
    {
        if (is_null($mechanics_info)) {
            throw new \InvalidArgumentException('non-nullable mechanics_info cannot be null');
        }
        $this->container['mechanics_info'] = $mechanics_info;

        return $this;
    }

    /**
     * Gets bestseller_info
     *
     * @return \YandexMarketApi\Model\GetPromoBestsellerInfoDTO
     */
    public function getBestsellerInfo()
    {
        return $this->container['bestseller_info'];
    }

    /**
     * Sets bestseller_info
     *
     * @param \YandexMarketApi\Model\GetPromoBestsellerInfoDTO $bestseller_info bestseller_info
     *
     * @return self
     */
    public function setBestsellerInfo($bestseller_info)
    {
        if (is_null($bestseller_info)) {
            throw new \InvalidArgumentException('non-nullable bestseller_info cannot be null');
        }
        $this->container['bestseller_info'] = $bestseller_info;

        return $this;
    }

    /**
     * Gets channels
     *
     * @return \YandexMarketApi\Model\ChannelType[]|null
     */
    public function getChannels()
    {
        return $this->container['channels'];
    }

    /**
     * Sets channels
     *
     * @param \YandexMarketApi\Model\ChannelType[]|null $channels Список каналов продвижения товаров.
     *
     * @return self
     */
    public function setChannels($channels)
    {
        if (is_null($channels)) {
            array_push($this->openAPINullablesSetToNull, 'channels');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('channels', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['channels'] = $channels;

        return $this;
    }

    /**
     * Gets constraints
     *
     * @return \YandexMarketApi\Model\GetPromoConstraintsDTO|null
     */
    public function getConstraints()
    {
        return $this->container['constraints'];
    }

    /**
     * Sets constraints
     *
     * @param \YandexMarketApi\Model\GetPromoConstraintsDTO|null $constraints constraints
     *
     * @return self
     */
    public function setConstraints($constraints)
    {
        if (is_null($constraints)) {
            throw new \InvalidArgumentException('non-nullable constraints cannot be null');
        }
        $this->container['constraints'] = $constraints;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


