<?php
/**
 * OrdersStatsPaymentSourceType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * OrdersStatsPaymentSourceType Class Doc Comment
 *
 * @category Class
 * @description Способ денежного перевода: - &#x60;BUYER&#x60; — оплата или возврат деньгами.  Устаревшие способы: - &#x60;CASHBACK&#x60;. - &#x60;MARKETPLACE&#x60;. - &#x60;SPLIT&#x60;.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrdersStatsPaymentSourceType
{
    /**
     * Possible values of this enum
     */
    public const BUYER = 'BUYER';

    public const CASHBACK = 'CASHBACK';

    public const MARKETPLACE = 'MARKETPLACE';

    public const SPLIT = 'SPLIT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BUYER,
            self::CASHBACK,
            self::MARKETPLACE,
            self::SPLIT
        ];
    }
}


