<?php
/**
 * OrderItemDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;

use \ArrayAccess;
use \YandexMarketApi\ObjectSerializer;

/**
 * OrderItemDTO Class Doc Comment
 *
 * @category Class
 * @description Список товаров в заказе.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrderItemDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrderItemDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'feed_id' => 'int',
        'offer_id' => 'string',
        'feed_category_id' => 'string',
        'offer_name' => 'string',
        'price' => 'float',
        'buyer_price' => 'float',
        'buyer_price_before_discount' => 'float',
        'price_before_discount' => 'float',
        'count' => 'int',
        'vat' => '\YandexMarketApi\Model\OrderVatType',
        'shop_sku' => 'string',
        'subsidy' => 'float',
        'partner_warehouse_id' => 'string',
        'promos' => '\YandexMarketApi\Model\OrderItemPromoDTO[]',
        'instances' => '\YandexMarketApi\Model\OrderItemInstanceDTO[]',
        'details' => '\YandexMarketApi\Model\OrderItemDetailDTO[]',
        'subsidies' => '\YandexMarketApi\Model\OrderItemSubsidyDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'feed_id' => 'int64',
        'offer_id' => null,
        'feed_category_id' => null,
        'offer_name' => null,
        'price' => 'decimal',
        'buyer_price' => 'decimal',
        'buyer_price_before_discount' => 'decimal',
        'price_before_discount' => 'decimal',
        'count' => null,
        'vat' => null,
        'shop_sku' => null,
        'subsidy' => 'decimal',
        'partner_warehouse_id' => null,
        'promos' => null,
        'instances' => null,
        'details' => null,
        'subsidies' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'feed_id' => false,
		'offer_id' => false,
		'feed_category_id' => false,
		'offer_name' => false,
		'price' => false,
		'buyer_price' => false,
		'buyer_price_before_discount' => false,
		'price_before_discount' => false,
		'count' => false,
		'vat' => false,
		'shop_sku' => false,
		'subsidy' => false,
		'partner_warehouse_id' => false,
		'promos' => false,
		'instances' => false,
		'details' => false,
		'subsidies' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'feed_id' => 'feedId',
        'offer_id' => 'offerId',
        'feed_category_id' => 'feedCategoryId',
        'offer_name' => 'offerName',
        'price' => 'price',
        'buyer_price' => 'buyerPrice',
        'buyer_price_before_discount' => 'buyerPriceBeforeDiscount',
        'price_before_discount' => 'priceBeforeDiscount',
        'count' => 'count',
        'vat' => 'vat',
        'shop_sku' => 'shopSku',
        'subsidy' => 'subsidy',
        'partner_warehouse_id' => 'partnerWarehouseId',
        'promos' => 'promos',
        'instances' => 'instances',
        'details' => 'details',
        'subsidies' => 'subsidies'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'feed_id' => 'setFeedId',
        'offer_id' => 'setOfferId',
        'feed_category_id' => 'setFeedCategoryId',
        'offer_name' => 'setOfferName',
        'price' => 'setPrice',
        'buyer_price' => 'setBuyerPrice',
        'buyer_price_before_discount' => 'setBuyerPriceBeforeDiscount',
        'price_before_discount' => 'setPriceBeforeDiscount',
        'count' => 'setCount',
        'vat' => 'setVat',
        'shop_sku' => 'setShopSku',
        'subsidy' => 'setSubsidy',
        'partner_warehouse_id' => 'setPartnerWarehouseId',
        'promos' => 'setPromos',
        'instances' => 'setInstances',
        'details' => 'setDetails',
        'subsidies' => 'setSubsidies'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'feed_id' => 'getFeedId',
        'offer_id' => 'getOfferId',
        'feed_category_id' => 'getFeedCategoryId',
        'offer_name' => 'getOfferName',
        'price' => 'getPrice',
        'buyer_price' => 'getBuyerPrice',
        'buyer_price_before_discount' => 'getBuyerPriceBeforeDiscount',
        'price_before_discount' => 'getPriceBeforeDiscount',
        'count' => 'getCount',
        'vat' => 'getVat',
        'shop_sku' => 'getShopSku',
        'subsidy' => 'getSubsidy',
        'partner_warehouse_id' => 'getPartnerWarehouseId',
        'promos' => 'getPromos',
        'instances' => 'getInstances',
        'details' => 'getDetails',
        'subsidies' => 'getSubsidies'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('feed_id', $data ?? [], null);
        $this->setIfExists('offer_id', $data ?? [], null);
        $this->setIfExists('feed_category_id', $data ?? [], null);
        $this->setIfExists('offer_name', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('buyer_price', $data ?? [], null);
        $this->setIfExists('buyer_price_before_discount', $data ?? [], null);
        $this->setIfExists('price_before_discount', $data ?? [], null);
        $this->setIfExists('count', $data ?? [], null);
        $this->setIfExists('vat', $data ?? [], null);
        $this->setIfExists('shop_sku', $data ?? [], null);
        $this->setIfExists('subsidy', $data ?? [], null);
        $this->setIfExists('partner_warehouse_id', $data ?? [], null);
        $this->setIfExists('promos', $data ?? [], null);
        $this->setIfExists('instances', $data ?? [], null);
        $this->setIfExists('details', $data ?? [], null);
        $this->setIfExists('subsidies', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['offer_id']) && (mb_strlen($this->container['offer_id']) > 80)) {
            $invalidProperties[] = "invalid value for 'offer_id', the character length must be smaller than or equal to 80.";
        }

        if (!is_null($this->container['offer_id']) && (mb_strlen($this->container['offer_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'offer_id', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['offer_id']) && !preg_match("/^[\\da-zA-ZА-Яа-я\\.,\/\\\\\\(\\)\\[\\]\\-=_]*$/", $this->container['offer_id'])) {
            $invalidProperties[] = "invalid value for 'offer_id', must be conform to the pattern /^[\\da-zA-ZА-Яа-я\\.,\/\\\\\\(\\)\\[\\]\\-=_]*$/.";
        }

        if (!is_null($this->container['shop_sku']) && (mb_strlen($this->container['shop_sku']) > 80)) {
            $invalidProperties[] = "invalid value for 'shop_sku', the character length must be smaller than or equal to 80.";
        }

        if (!is_null($this->container['shop_sku']) && (mb_strlen($this->container['shop_sku']) < 1)) {
            $invalidProperties[] = "invalid value for 'shop_sku', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['shop_sku']) && !preg_match("/^[\\da-zA-ZА-Яа-я\\.,\/\\\\\\(\\)\\[\\]\\-=_]*$/", $this->container['shop_sku'])) {
            $invalidProperties[] = "invalid value for 'shop_sku', must be conform to the pattern /^[\\da-zA-ZА-Яа-я\\.,\/\\\\\\(\\)\\[\\]\\-=_]*$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id Идентификатор товара в заказе.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets feed_id
     *
     * @return int|null
     */
    public function getFeedId()
    {
        return $this->container['feed_id'];
    }

    /**
     * Sets feed_id
     *
     * @param int|null $feed_id Идентификатор каталога товаров.
     *
     * @return self
     */
    public function setFeedId($feed_id)
    {
        if (is_null($feed_id)) {
            throw new \InvalidArgumentException('non-nullable feed_id cannot be null');
        }
        $this->container['feed_id'] = $feed_id;

        return $this;
    }

    /**
     * Gets offer_id
     *
     * @return string|null
     */
    public function getOfferId()
    {
        return $this->container['offer_id'];
    }

    /**
     * Sets offer_id
     *
     * @param string|null $offer_id **Ваш SKU**  Идентификатор товара в магазине. Разрешены английские и русские буквы (кроме ё), цифры и символы `. , / \\ ( ) [ ] - = _`  Максимальная длина — 80 знаков.  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields).
     *
     * @return self
     */
    public function setOfferId($offer_id)
    {
        if (is_null($offer_id)) {
            throw new \InvalidArgumentException('non-nullable offer_id cannot be null');
        }
        if ((mb_strlen($offer_id) > 80)) {
            throw new \InvalidArgumentException('invalid length for $offer_id when calling OrderItemDTO., must be smaller than or equal to 80.');
        }
        if ((mb_strlen($offer_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $offer_id when calling OrderItemDTO., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[\\da-zA-ZА-Яа-я\\.,\/\\\\\\(\\)\\[\\]\\-=_]*$/", $offer_id))) {
            throw new \InvalidArgumentException("invalid value for \$offer_id when calling OrderItemDTO., must conform to the pattern /^[\\da-zA-ZА-Яа-я\\.,\/\\\\\\(\\)\\[\\]\\-=_]*$/.");
        }

        $this->container['offer_id'] = $offer_id;

        return $this;
    }

    /**
     * Gets feed_category_id
     *
     * @return string|null
     */
    public function getFeedCategoryId()
    {
        return $this->container['feed_category_id'];
    }

    /**
     * Sets feed_category_id
     *
     * @param string|null $feed_category_id Идентификатор категории, указанный в каталоге.
     *
     * @return self
     */
    public function setFeedCategoryId($feed_category_id)
    {
        if (is_null($feed_category_id)) {
            throw new \InvalidArgumentException('non-nullable feed_category_id cannot be null');
        }
        $this->container['feed_category_id'] = $feed_category_id;

        return $this;
    }

    /**
     * Gets offer_name
     *
     * @return string|null
     */
    public function getOfferName()
    {
        return $this->container['offer_name'];
    }

    /**
     * Sets offer_name
     *
     * @param string|null $offer_name Название товара.
     *
     * @return self
     */
    public function setOfferName($offer_name)
    {
        if (is_null($offer_name)) {
            throw new \InvalidArgumentException('non-nullable offer_name cannot be null');
        }
        $this->container['offer_name'] = $offer_name;

        return $this;
    }

    /**
     * Gets price
     *
     * @return float|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param float|null $price Цена товара в валюте заказа без учета вознаграждения партнеру за скидки по промокодам, купонам и акциям (параметр `subsidy`).  Для отделения целой части от дробной используется точка.
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets buyer_price
     *
     * @return float|null
     */
    public function getBuyerPrice()
    {
        return $this->container['buyer_price'];
    }

    /**
     * Sets buyer_price
     *
     * @param float|null $buyer_price Цена товара в валюте покупателя. В цене уже учтены скидки по:  * акциям; * купонам; * промокодам.  Для отделения целой части от дробной используется точка.
     *
     * @return self
     */
    public function setBuyerPrice($buyer_price)
    {
        if (is_null($buyer_price)) {
            throw new \InvalidArgumentException('non-nullable buyer_price cannot be null');
        }
        $this->container['buyer_price'] = $buyer_price;

        return $this;
    }

    /**
     * Gets buyer_price_before_discount
     *
     * @return float|null
     */
    public function getBuyerPriceBeforeDiscount()
    {
        return $this->container['buyer_price_before_discount'];
    }

    /**
     * Sets buyer_price_before_discount
     *
     * @param float|null $buyer_price_before_discount Стоимость товара в валюте покупателя до применения скидок.  Для отделения целой части от дробной используется точка.
     *
     * @return self
     */
    public function setBuyerPriceBeforeDiscount($buyer_price_before_discount)
    {
        if (is_null($buyer_price_before_discount)) {
            throw new \InvalidArgumentException('non-nullable buyer_price_before_discount cannot be null');
        }
        $this->container['buyer_price_before_discount'] = $buyer_price_before_discount;

        return $this;
    }

    /**
     * Gets price_before_discount
     *
     * @return float|null
     */
    public function getPriceBeforeDiscount()
    {
        return $this->container['price_before_discount'];
    }

    /**
     * Sets price_before_discount
     *
     * @param float|null $price_before_discount Стоимость товара в валюте магазина до применения скидок.  Для отделения целой части от дробной используется точка.
     *
     * @return self
     */
    public function setPriceBeforeDiscount($price_before_discount)
    {
        if (is_null($price_before_discount)) {
            throw new \InvalidArgumentException('non-nullable price_before_discount cannot be null');
        }
        $this->container['price_before_discount'] = $price_before_discount;

        return $this;
    }

    /**
     * Gets count
     *
     * @return int|null
     */
    public function getCount()
    {
        return $this->container['count'];
    }

    /**
     * Sets count
     *
     * @param int|null $count Количество товара.
     *
     * @return self
     */
    public function setCount($count)
    {
        if (is_null($count)) {
            throw new \InvalidArgumentException('non-nullable count cannot be null');
        }
        $this->container['count'] = $count;

        return $this;
    }

    /**
     * Gets vat
     *
     * @return \YandexMarketApi\Model\OrderVatType|null
     */
    public function getVat()
    {
        return $this->container['vat'];
    }

    /**
     * Sets vat
     *
     * @param \YandexMarketApi\Model\OrderVatType|null $vat vat
     *
     * @return self
     */
    public function setVat($vat)
    {
        if (is_null($vat)) {
            throw new \InvalidArgumentException('non-nullable vat cannot be null');
        }
        $this->container['vat'] = $vat;

        return $this;
    }

    /**
     * Gets shop_sku
     *
     * @return string|null
     */
    public function getShopSku()
    {
        return $this->container['shop_sku'];
    }

    /**
     * Sets shop_sku
     *
     * @param string|null $shop_sku **Ваш SKU**  Идентификатор товара в магазине. Разрешены английские и русские буквы (кроме ё), цифры и символы `. , / \\ ( ) [ ] - = _`  Максимальная длина — 80 знаков.  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields).
     *
     * @return self
     */
    public function setShopSku($shop_sku)
    {
        if (is_null($shop_sku)) {
            throw new \InvalidArgumentException('non-nullable shop_sku cannot be null');
        }
        if ((mb_strlen($shop_sku) > 80)) {
            throw new \InvalidArgumentException('invalid length for $shop_sku when calling OrderItemDTO., must be smaller than or equal to 80.');
        }
        if ((mb_strlen($shop_sku) < 1)) {
            throw new \InvalidArgumentException('invalid length for $shop_sku when calling OrderItemDTO., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[\\da-zA-ZА-Яа-я\\.,\/\\\\\\(\\)\\[\\]\\-=_]*$/", $shop_sku))) {
            throw new \InvalidArgumentException("invalid value for \$shop_sku when calling OrderItemDTO., must conform to the pattern /^[\\da-zA-ZА-Яа-я\\.,\/\\\\\\(\\)\\[\\]\\-=_]*$/.");
        }

        $this->container['shop_sku'] = $shop_sku;

        return $this;
    }

    /**
     * Gets subsidy
     *
     * @return float|null
     */
    public function getSubsidy()
    {
        return $this->container['subsidy'];
    }

    /**
     * Sets subsidy
     *
     * @param float|null $subsidy Общее вознаграждение партнеру за все скидки на товар:  * по промокодам; * по купонам; * по баллам кешбэка по подписке Яндекс Плюс; * по акциям.  Передается в валюте заказа, для отделения целой части от дробной используется точка.
     *
     * @return self
     */
    public function setSubsidy($subsidy)
    {
        if (is_null($subsidy)) {
            throw new \InvalidArgumentException('non-nullable subsidy cannot be null');
        }
        $this->container['subsidy'] = $subsidy;

        return $this;
    }

    /**
     * Gets partner_warehouse_id
     *
     * @return string|null
     */
    public function getPartnerWarehouseId()
    {
        return $this->container['partner_warehouse_id'];
    }

    /**
     * Sets partner_warehouse_id
     *
     * @param string|null $partner_warehouse_id Идентификатор склада в системе партнера, на который сформирован заказ.  {% note alert %}  Параметр устарел, временно поддерживается, но не доступен для ввода и редактирования.  {% endnote %}
     *
     * @return self
     */
    public function setPartnerWarehouseId($partner_warehouse_id)
    {
        if (is_null($partner_warehouse_id)) {
            throw new \InvalidArgumentException('non-nullable partner_warehouse_id cannot be null');
        }
        $this->container['partner_warehouse_id'] = $partner_warehouse_id;

        return $this;
    }

    /**
     * Gets promos
     *
     * @return \YandexMarketApi\Model\OrderItemPromoDTO[]|null
     */
    public function getPromos()
    {
        return $this->container['promos'];
    }

    /**
     * Sets promos
     *
     * @param \YandexMarketApi\Model\OrderItemPromoDTO[]|null $promos Информация о вознаграждениях партнеру за скидки на товар по промокодам, купонам и акциям.
     *
     * @return self
     */
    public function setPromos($promos)
    {
        if (is_null($promos)) {
            throw new \InvalidArgumentException('non-nullable promos cannot be null');
        }
        $this->container['promos'] = $promos;

        return $this;
    }

    /**
     * Gets instances
     *
     * @return \YandexMarketApi\Model\OrderItemInstanceDTO[]|null
     */
    public function getInstances()
    {
        return $this->container['instances'];
    }

    /**
     * Sets instances
     *
     * @param \YandexMarketApi\Model\OrderItemInstanceDTO[]|null $instances Информация о маркировке единиц товара.  Возвращаются данные для маркировки, переданные в запросе `PUT /campaigns/{campaignId}/orders/{orderId}/cis`.  Если магазин еще не передавал коды для этого заказа, `instances` отсутствует.
     *
     * @return self
     */
    public function setInstances($instances)
    {
        if (is_null($instances)) {
            throw new \InvalidArgumentException('non-nullable instances cannot be null');
        }
        $this->container['instances'] = $instances;

        return $this;
    }

    /**
     * Gets details
     *
     * @return \YandexMarketApi\Model\OrderItemDetailDTO[]|null
     */
    public function getDetails()
    {
        return $this->container['details'];
    }

    /**
     * Sets details
     *
     * @param \YandexMarketApi\Model\OrderItemDetailDTO[]|null $details Информация об удалении товара из заказа.
     *
     * @return self
     */
    public function setDetails($details)
    {
        if (is_null($details)) {
            throw new \InvalidArgumentException('non-nullable details cannot be null');
        }
        $this->container['details'] = $details;

        return $this;
    }

    /**
     * Gets subsidies
     *
     * @return \YandexMarketApi\Model\OrderItemSubsidyDTO[]|null
     */
    public function getSubsidies()
    {
        return $this->container['subsidies'];
    }

    /**
     * Sets subsidies
     *
     * @param \YandexMarketApi\Model\OrderItemSubsidyDTO[]|null $subsidies Список субсидий по типам.
     *
     * @return self
     */
    public function setSubsidies($subsidies)
    {
        if (is_null($subsidies)) {
            throw new \InvalidArgumentException('non-nullable subsidies cannot be null');
        }
        $this->container['subsidies'] = $subsidies;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


