<?php
/**
 * RegionType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * RegionType Class Doc Comment
 *
 * @category Class
 * @description Тип региона.  Возможные значения:  * &#x60;CITY_DISTRICT&#x60; — район города.  * &#x60;CITY&#x60; — крупный город.  * &#x60;CONTINENT&#x60; — континент.  * &#x60;COUNTRY_DISTRICT&#x60; — область.  * &#x60;COUNTRY&#x60; — страна.  * &#x60;REGION&#x60; — регион.  * &#x60;REPUBLIC_AREA&#x60; — район субъекта федерации.  * &#x60;REPUBLIC&#x60; — субъект федерации.  * &#x60;SUBWAY_STATION&#x60; — станция метро.  * &#x60;VILLAGE&#x60; — город.  * &#x60;OTHER&#x60; — неизвестный регион.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RegionType
{
    /**
     * Possible values of this enum
     */
    public const OTHER = 'OTHER';

    public const CONTINENT = 'CONTINENT';

    public const REGION = 'REGION';

    public const COUNTRY = 'COUNTRY';

    public const COUNTRY_DISTRICT = 'COUNTRY_DISTRICT';

    public const REPUBLIC = 'REPUBLIC';

    public const CITY = 'CITY';

    public const VILLAGE = 'VILLAGE';

    public const CITY_DISTRICT = 'CITY_DISTRICT';

    public const SUBWAY_STATION = 'SUBWAY_STATION';

    public const REPUBLIC_AREA = 'REPUBLIC_AREA';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OTHER,
            self::CONTINENT,
            self::REGION,
            self::COUNTRY,
            self::COUNTRY_DISTRICT,
            self::REPUBLIC,
            self::CITY,
            self::VILLAGE,
            self::CITY_DISTRICT,
            self::SUBWAY_STATION,
            self::REPUBLIC_AREA
        ];
    }
}


