<?php
/**
 * ReportFormatType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * ReportFormatType Class Doc Comment
 *
 * @category Class
 * @description Формат отчета:  * &#x60;FILE&#x60; — файл с электронной таблицей (XLSX). * &#x60;CSV&#x60; — ZIP-архив с CSV-файлами на каждый лист отчета. * &#x60;JSON&#x60; — ZIP-архив с JSON-файлами на каждый лист отчета.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReportFormatType
{
    /**
     * Possible values of this enum
     */
    public const FILE = 'FILE';

    public const CSV = 'CSV';

    public const JSON = 'JSON';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FILE,
            self::CSV,
            self::JSON
        ];
    }
}


