<?php
/**
 * BenefitTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace YandexMarketApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BenefitTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Типы дополнительных инструментов продвижения:  * &#x60;BESTS&#x60; — участие в акции «Бестселлеры Маркета». * &#x60;SPLIT_0_0_4&#x60; — возможность оплаты со Сплитом сроком на 4 месяца. * &#x60;SPLIT_0_0_6&#x60; — возможность оплаты со Сплитом сроком на 6 месяцев. * &#x60;SPLIT_0_0_12&#x60; — возможность оплаты со Сплитом сроком на 12 месяцев. * &#x60;MARKET_SUBSIDY_1_4&#x60; — скидка от Маркета от 1 до 4%. * &#x60;MARKET_SUBSIDY_5_9&#x60; — скидка от Маркета от 5 до 9%. * &#x60;MARKET_SUBSIDY_10&#x60; — скидка от Маркета от 10%.
 * @package     YandexMarketApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BenefitTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BenefitType"
     */
    public function testBenefitType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
