<?php
/**
 * OrderStatsStatusTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace YandexMarketApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OrderStatsStatusTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Текущий статус заказа:  * &#x60;CANCELLED_BEFORE_PROCESSING&#x60; — заказ отменен до начала его обработки;  * &#x60;CANCELLED_IN_DELIVERY&#x60; — заказ отменен во время его доставки;  * &#x60;CANCELLED_IN_PROCESSING&#x60; — заказ отменен во время его обработки;  * &#x60;DELIVERY&#x60; — заказ передан службе доставки;  * &#x60;DELIVERED&#x60; — заказ доставлен;  * &#x60;PARTIALLY_RETURNED&#x60; — заказ частично возвращен покупателем;  * &#x60;PICKUP&#x60; — заказ доставлен в пункт выдачи;      * Значение по умолчанию: &#x60;PICKUP_SERVICE_RECEIVED&#x60;;      * &#x60;PICKUP_USER_RECEIVED&#x60; – покупатель получил заказ.  * &#x60;PROCESSING&#x60; — заказ в обработке;  * &#x60;REJECTED&#x60; — заказ создан, но не оплачен;  * &#x60;RETURNED&#x60; — заказ полностью возвращен покупателем;  * &#x60;UNKNOWN&#x60; — неизвестный статус заказа.
 * @package     YandexMarketApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OrderStatsStatusTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderStatsStatusType"
     */
    public function testOrderStatsStatusType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
