<?php
/**
 * ReturnDecisionReasonTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace YandexMarketApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ReturnDecisionReasonTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Причины возврата:  * BAD_QUALITY — бракованный товар (есть недостатки).  * DO_NOT_FIT — товар не подошел.  * WRONG_ITEM — привезли не тот товар.  * DAMAGE_DELIVERY — товар поврежден при доставке.  * LOYALTY_FAIL — невозможно установить виновного в браке/пересорте.  * CONTENT_FAIL — ошибочное описание товара по вине Маркета.  * UNKNOWN — причина не известна.
 * @package     YandexMarketApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReturnDecisionReasonTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReturnDecisionReasonType"
     */
    public function testReturnDecisionReasonType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
